### ISSUE TITLE
Oracle attack using "Resend Account Information" and "Resend Confirmation Email"

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#118]
Using the resend email features, an attacker can determine whether or not an email is currently in use by one of our players. This means that

1) if they want to know if a specific person has an account here, they can find out
2) if they want to automatically find emails they can use to create dupe accounts with, they can

Resolution: we should not be providing this information via the web. It is probably safer to send an email that says the same thing.

**Comment by tchalvak** [comment]
Wontfix
