### ISSUE TITLE
No check for null clan_id in clan.php.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#170]
Exception message: exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""' in /home/ninjawars/game/live/lib/data/lib_db.php:31
Stack trace:
#0 /home/ninjawars/game/live/lib/data/lib_db.php(31): PDOStatement->execute()
#1 /home/ninjawars/game/live/lib/data/lib_db.php(43): query('SELECT clan_id,...', Array, true)
#2 /home/ninjawars/game/live/lib/data/lib_db.php(53): query_resultset('SELECT clan_id,...', Array)
#3 /home/ninjawars/game/live/lib/control/lib_clan.php(184): query_row('SELECT clan_id,...', Array)
#4 /home/ninjawars/game/live/lib/control/lib_clan.php(176): clan_info('')
#5 /home/ninjawars/game/live/www/clan.php(264): get_clan('')
#6 {main}

REQUEST_URI: /clan.php?command=view&clan_id=
REFERER:
METHOD: GET

**Comment by Beagle** [comment]
ClanController handles this case properly now.
