### ISSUE TITLE
Migrate over to password_hash functions instead of direct bcrypt usage.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#219]

**Comment by Beagle** [comment]
@tchalvak The application is not using direct bcrypt. It is delegating password hashing to the database and no hashing is happening in PHP. I recommend closing this issue or rewording it to factoring password hashing out of the DB and into the application.

**Comment by tchalvak** [comment]
That is what this issue is about, yes, password_hash in php to decrease password capture surface. We can discuss when I'm not on mobile.

**Comment by tchalvak** [comment]
This may simply be a "need https" problem, and deserves being part of a general security brainstorm/discussion/audit.

**Comment by tchalvak** [comment]
Closing this in favor of a "do we need https?" issue.
