### ISSUE TITLE
DimMak message is bad.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#229]
Quote:
Bravos takes 1 damage.

be drained of your life-force and die!

You have killed Bravos with a Dim Mak!
You receive 204 gold from Bravos.
You have received the 5000 gold bounty on Bravos's head for your deeds!

Multiple things wrong with it here.

**Comment by Beagle** [comment]
@tchalvak Please provide acceptance criteria for this issue so that it can be addressed.

**Comment by tchalvak** [comment]
A.C.:  
kill with dim mak ->
- sends message to victim with proper grammar.
- page displays to attacker thematic description of life drain effect

**Comment by tchalvak** [comment]
Fixed in 3393a4f4d1f007f2a44526990b2a0de2c2592eed
