### ISSUE TITLE
As a player, my class, level, and current gold are permanently visible on screen and up-to-date within 3 seconds of a change

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#231]

**Comment by tchalvak** [comment]
Can just put it in the avatar dropdown area.

**Comment by tchalvak** [comment]
A.C.:
- Class & Level don't take up important space, aren't distracting
- These datum update when the user changes them (through class change, via levelling up, respectively)
- Subtle styling

**Comment by tchalvak** [comment]
Level is actually in the ninja-menu for now, as for the rest, let's just deal with them on an individual basis as needed.  I don't really know that getting into a whole new async system (or rather, piggybacking on the current system used for health/turns/kills on the index page now) for updating gold, class, and level is a direction that we want to deal with today.
