### ISSUE TITLE
Move all integration tests out of tests/unit/ and into tests/integration/

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#240]
AC:
1) All tests in tests/unit do not rely on database, cache, native PHP session superglobal, native PHP request superglobal, native PHP server superglobal, a web server, and a PHP application server
2) Unit tests and Integration tests can be run independently
3) Code coverage reports are only generated when running unit tests

**Comment by tchalvak** [comment]
Hmmm

**Comment by tchalvak** [comment]
If you want to do this for name change, do it.  Just make surea single command still runs my existing tests afterwards & it's easy to swap the ci to using the integration tests.

**Comment by tchalvak** [comment]
I've been considering this since you introduced it, and I think I'm more interested in it now.
