### ISSUE TITLE
Create ShrineController to encapsulate logic in shrine.php and shrine_mod.php

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#244]
AC:
1) A ShrineController class is defined in a file in /lib/control/ShrineController.php
2) Public methods on ShrineController return a view spec hash
3) All shrine actions behave the same way as they do before the refactor with respect to state change
4) shrine_mod.php is deleted
5) all shrine display logic is handled by a single master template and many sub-templates

**Comment by tchalvak** [comment]
See the regression notes I made on the pull request a few days ago, unless you want me to dig into them.
