### ISSUE TITLE
As a developer, our tests are stored in the root of the repository to separate them from the application source code.

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#246]
Tests are not deployed. Tests are used to test the code in deploy. The current directory tree requires test configuration to explicitly ignore itself. Move /deploy/tests/ to /tests/

**Comment by tchalvak** [comment]
Then how will tests be run in a deployed instance?

**Comment by Beagle** [comment]
I believe there's a better way to address the need you are expressing than the current way. I will research and get back to you.

**Comment by tchalvak** [comment]
I'm going to mark this as wont-fix because in recent development I've been finding the opposite to be recommended: Move your tests right up in with each component that you develop, so that they're very close to each part.
