### ISSUE TITLE
Remove unnecessary docs

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#247]
Consider removing the following files because they add nothing:
* docs/gitLogUntilApril2nd2009

Consider removing the following files because they are generic documentation for external utilities and * applications (like git, find, postgresql, etc):
* docs/gitNinjawars.txt
* docs/cherry-pick-a-range-of-commits.txt
* docs/sampleHomeFolderDOTgitconfig
* docs/search_and_replace.txt
* docs/wintermuteSamplEpg_hbaDOTconf

Consider removing the following files because they are empty:
* docs/harkSAMPLEhtaccess

**Comment by tchalvak** [comment]
Fixed in e4793db526022facaa16ac7fd020c8db44de7c39 
Note that there was an existing CODING_STANDARDS document!  : D
