### ISSUE TITLE
Fix undefined index error for "type_filter" in messages.nav.tpl

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#259]
PHP Notice:  Undefined index: type_filter

AC:
1) Either type_filter is defined or the need for it is removed
2) The error is not suppressed

**Comment by tchalvak** [comment]
Cannot replicate this in dev, are you getting this in the error log?  Please paste the whole log, and the url.

**Comment by Beagle** [comment]
Steps to reproduce: click on the link the header to http://nw.localhost/messages.php (the message box with the number counter)

PHP message: PHP Notice:  Undefined index: type_filter in /home/beagle/projects/gamedev/nw1/ninjawars/deploy/templates/compiled/fd0ea786a32f9f5f42881432abcf6aacc3285c75.file.messages.nav.tpl.php on line 46
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/www/messages.php:0
PHP message: PHP   2. display_page() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/www/messages.php:114
PHP message: PHP   3. NWTemplate->fullDisplay() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/control/lib_templates.php:77
PHP message: PHP   4. Smarty_Internal_TemplateBase->display() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/control/lib_templates.php:28
PHP message: PHP   5. Smarty_Internal_TemplateBase->fetch() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:394
PHP message: PHP   6. content_562aec96c1f974_65018113() /home/beagle/projects/gamedev/nw1/ninjawars/deploy/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:188

etc

**Comment by tchalvak** [comment]
Fixed in 97c22a5f3eecc97fd6a39465f5e4546799580836
