### ISSUE TITLE
Create an ActiveRecord Model for Player

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#263]
AC:
*) Ability to retrieve a player object by surrogate key (player id)
*) Ability to retrieve a player by username
*) case-insensitive white-space tolerant unique username is enforced when creating and updating users
*) username is trimmed of whitespace when writing to state
*) A unit test can be written that uses a player mock without needing any database connection at all
*) CasinoController uses the player model
*) DoshinController uses the player model

**Comment by tchalvak** [comment]
@beagle I don't have a solution for this at this time, I would say it's premature until we have like 3-4 more eloquent models in the nw codebase, and then we can revisit Player.

**Comment by tchalvak** [comment]
![i_guess_animated](https://cloud.githubusercontent.com/assets/23353/13724181/d2345f3e-e84a-11e5-9b71-51ac800132d3.gif)
