### ISSUE TITLE
Do we need/can we support https?

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#269]
To prevent MiTM attacks on login, and cookie stealing.

Pros: 
- Security benefits
- Industry Standard, These days

Cons:
- will have to do URL rewrites
- Potential SEO ranking decrease from urls changing
- Requires doubling the load balancers

**Comment by chrisdotcode** [comment]
http://blog.codinghorror.com/should-all-web-traffic-be-encrypted/

**Comment by tchalvak** [comment]
Yeah, it's definitely something that I like to do on any modern site.  It's just because ninjawars is: A: a game and B: an older site; that I am weighing the pros & cons before deciding whether to engage.

**Comment by tchalvak** [comment]
SSL is currently almost all working at: https://ssl.ninjawars.net
