### ISSUE TITLE
As a player, I want USE in the most prominent and obvious position, not "GIVE".

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#271]
To give the more frequently used action the better UX position.
Acceptance Criteria:
- swap positions of GIVE with USE on pc profile page.

**Comment by tchalvak** [comment]
http://imgur.com/SiuVJMu

**Comment by tchalvak** [comment]
![siuvjmu - imgur](https://cloud.githubusercontent.com/assets/23353/11275634/945686bc-8eac-11e5-9fa4-8c55d3c84dd6.jpg)

**Comment by Beagle** [comment]
@tchalvak Is this complete?

**Comment by tchalvak** [comment]
Nope.
