### ISSUE TITLE
As a hardcore min/max gamer, when I perform a stealthed, single-attack kill I get a clear message.

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#273]

**Comment by tchalvak** [comment]
Just tested, unable to replicate as reported:
*  Tchalvak has used a Phosphor Powder on you at October 29, 2015, 9:56 pm and caused you to take 96 damage!
   | wthfisthis
  * DEATH: You've been killed by Tchalvak and lost 0 gold on October 29, 2015, 9:55 pm!
   | BackLash
  * You have been dueled by Tchalvak at October 29, 2015, 9:55 pm for 259!
   | BackLash
  * Tchalvak has attacked you from the shadows for 132 damage.
   | Alan
 *  Tchalvak has attacked you from the shadows for 132 damage.
   | LordL3go

Please clarify.

**Comment by tchalvak** [comment]
Closing as cannot reproduce.

**Comment by tchalvak** [comment]
Ok, to replicate:
Get a pc target down to low health, e.g. < 100 health.
Stealth yourself.
Perform a standard attack on target (no duel, no deflect).
