### ISSUE TITLE
Clan: As a developer I should have at least one docblock per clan controller method.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#278]
Please docblock the clan controller methods at your convenience.

**Comment by tchalvak** [comment]
The docblock syntax & ordering was screwed up.

**Comment by tchalvak** [comment]
@beagle This is the correct docblock syntax for php:
http://phpdoc.org/docs/latest/references/phpdoc/types.html

type [$varname] description
type can be multiple: int|null

**Comment by Beagle** [comment]
Thanks for catching and fixing the error. Hadn't even realized it
