### ISSUE TITLE
Refactor all session code to use Symfony\Component\HttpFoundation\Session

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#290]
AC:
1) deploy/lib/control/Session.class.php is removed from source tree
2) Game still runs after deleting deploy/lib/control/Session.class.php
3) `make test` still completes successfully after deleting deploy/lib/control/Session.class.php
4) Login, logout, and all other game pages run after deleting deploy/lib/control/Session.class.php
5) `grep -rq 'session_' *` returns false
6) 'grep -rq '_SESSION' *` returns false

**Comment by tchalvak** [comment]
+1

**Comment by tchalvak** [comment]
See login bug introduced by the pull request here: https://github.com/BitLucid/ninjawars/pull/323#issuecomment-164782028
