### ISSUE TITLE
As a developer, I want the signup page to use the front-controller for public access and a controller for its logic

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#292]
Acceptance Criteria:
- have a SignupController with index action
- have a SignupController with request POST action
- signup.php uses only the controller internally and has only generic logic in it

**Comment by Beagle** [comment]
http://blog.codinghorror.com/flattening-arrow-code/

**Comment by tchalvak** [comment]
Related regression: #405
