### ISSUE TITLE
Chat ago time is not reactive, and thus is generally wrong.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#30]
Since the "x <time> ago" message in the chat is loaded only when new chats get loaded, by php and not via javascript, the latest chat message will pretty much always reflect the latest point at which the page was loaded, -not- the amount of time ago that the chat was made.

In other words, all the "ago" messages are usually wrong because they do not update their time.  The latest chat will often say "(0 minutes ago)" but in reality have been posed who knows how long ago.  Those ago messages should use the javascript jQuery timeago plugin instead: http://timeago.yarp.com/
I actually started setting up the chat to use that system, but haven't completed it.

**Comment by Beagle** [comment]
@tchalvak This issue is 5 years old. Consider closing it as obsolete please define some acceptance criteria so this may be addressed.

**Comment by tchalvak** [comment]
Ok.

**Comment by tchalvak** [comment]
Oh, actually I think this is fixed now technically (by merit of time ago used everywhere except minichat, and minichat not displaying time stamps any more for this very reason)
