### ISSUE TITLE
As a developer, I want all variable names in lib_auth that are shorter than 3 and longer than 20 to be renamed to make the code easier to understand

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#304]
Also, to reduce code quality analysis issue notices because useless notices breed a culture of ignoring notices. We need higher signal-to-noise. This task will reduce some of the noise.

**Comment by tchalvak** [comment]
I will accept this change, but I reject the validity of the rationale above.  Noise is just noise, it should not gain priority simply because it's slightly annoying.  Reduce the background noise audio feedback by turning down your speaker volume from 11.
