### ISSUE TITLE
As a developer, I want to pull the raw data for a player sometimes, without a lot of additional overhead.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#314]
This would replace calls to char_info(self_char_id()) used in lib_api currently (and elsewhere probably).

Should be used sparingly, with `Player::find($id)` used much more often.
`$player->data()` currently exists, but since it's not static, you have to instantiate a full player object before getting just an array of data, so a static would be better.

For example:

```
$data = Player::data($id);
```

AC:
- Get raw data of a player via call to a static method on the Player object
- Don't have to instantiate the player object to get the info
- char_info is marked as deprecated

**Comment by tchalvak** [comment]
Exists in the form of Player->data() instance method, maybe still need a static method through.

**Comment by Beagle** [comment]
@tchalvak Please review this and consider closing it or adding clearer AC

**Comment by tchalvak** [comment]
@beagle clarified AC

**Comment by tchalvak** [comment]
This still has the issue that you have to instantiate a whole player object, just to get some simple raw data on the player in array form.  Seems excessive, and certainly won't make function char_info() replaceable as is (for example when displaying lots of players without a lot of behavior, as in the enemies list).

**Comment by Beagle** [comment]
Understood, this is achievable and ready to be worked on

**Comment by tchalvak** [comment]
Hmmm, this would also be especially useful for the API, where we may not really need the full player object, so much as it's data.  Going to move this into the Speed/Performance milestone.

**Comment by tchalvak** [comment]
I think I implemented in-code solutions for this, good enough, closing.
