### ISSUE TITLE
As a developer, I want to gut & simplify lib_player functions.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#330]
https://github.com/BitLucid/ninjawars/blob/5b8ba9fcf21895204b95658ce82b19f7608bd278/deploy/lib/control/lib_auth.php

self_name() is an example that deserves removal, among others.

**Comment by tchalvak** [comment]
get_char_name() and possibly get_char_id() and ninja_id() need to be examined as well.

**Comment by tchalvak** [comment]
membership_and_combat_stats() probably could be turned into some kind of static object.  I don't think it's used much of anywhere except duel.php

**Comment by tchalvak** [comment]
Probably dependent upon or related to #356

**Comment by tchalvak** [comment]
Taking this issue out of "ready" because I'm going to say it's dependent on #356 happening -FIRST- (or maybe concurrently).

**Comment by Beagle** [comment]
lib_player.php is removed from the game
