### ISSUE TITLE
Consider inserting a cms/static page generator in front of the core gameplay of the site.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#331]
Part of the reason that the look & feel of the site is so... ..old school is that there's no CMS system in place for the site.  And rolling our own wouldn't be the best use of our time.  So perhaps we should consider integrating a "front" to the site that would use a cms, and migrating the various guide pages (e.g. staff.php, http://www.ninjawars.net/#tutorial.php, http://www.ninjawars.net/#news.php, http://www.ninjawars.net/#rules.php, and probably the homepage itself, to using a cms or static page generator like https://sculpin.io/ to generate the standard content, and then exclude routes for the game).

@Beagle thoughts?

**Comment by Beagle** [comment]
I would avoid using a database-driven CMS. I like the idea of the static
publishing process by which we create a publishing specification, source
material for the content, and then have the content rendered during the
build/deploy process. Not sure though.

**Comment by tchalvak** [comment]
Mmmhmmm, I'll experiment in another repository with sculpin.

**Comment by tchalvak** [comment]
Checking out https://github.com/lektor/lektor

**Comment by tchalvak** [comment]
I'm still planning on checking out sculpin at a later point, just haven't gotten to that yet.  Lektor won't quite work because it relies on /directory/ directories being created, which is rather disruptive and messy when you're -also- doing manual coding on a codebase.

**Comment by tchalvak** [comment]
Thought about it, it's cool, but haven't found a solution yet.
