### ISSUE TITLE
Asset Generation: As a dev, Beagle wants to pull in jQuery (and other third-parties) automatically.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#336]
We currently don't have a way that static js/css assets can be pulled in to the project.  We need to be able to pull in jQuery (easy), and then put it into place (and prevent old versions from being cached on the front-end).
- Also jquery.linkify
- Also jQuery.timeago
- Also bootstrap.css eventually.

AC:
 - Specify the jQuery version wanted.
 - Pull in jQuery version automatically.
 - (optionally) minify & concatenate scripts?
 - Pull in at least one other third-party lib in the same way.

**Comment by tchalvak** [comment]
@beagle I'm just going to close this as wontfix, without a solution.  I don't have a good solution, and you're the one who (presumably) wants jQuery out of the codebase for your metrics.

Wontfix.

**Comment by Beagle** [comment]
I'll handle it then
