### ISSUE TITLE
Stack Challenge: Al (◉౪◉) wants to prove that we can build an actual stack around the current refactoring efforts.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#338]
We need proof that our current refactoring approach is something that will actually work for us as we move forward. Right now Al is certain it will.  I feel we should start incorporating a microframework to help get the structure more regular.  Al's challenge is to prove we don't need to.  In fact, Al says that we're almost able to do so already and that it won't take time to get the whole stack in operation.  So let's see him prove it.

The acceptance criteria are:

1. A dev can add an arbitrary new "page/controller" just by; adding a controller, adding a `require`, and modifying an nginx location block.
2. A dev can use pretty urls for such a new controller.
3. Al can replace two scripts in /www/ with the system.
4. (optional) A dev can add new "page/controller"s without modifying nginx.

Failure condition:
- Tighten up your sphincters for ninjawars codebase getting a microframework incorporated (Lumen or Silex). (╯°□°）╯︵ ┻━┻

**Comment by tchalvak** [comment]
https://github.com/BitLucid/ninjawars/tree/stack-challenge-338

**Comment by Beagle** [comment]
@tchalvak Please review this 20 point story. I love me some point!

**Comment by tchalvak** [comment]
The implications of this are HUGE: single location for includes, single location for error checking, phasing out of autoprepend, autoloading, and in general the potential for the "ninjawars app" to actually be able to coalesce around something that looks like a true application structure.

I still haven't actually gotten to the testing phase, but regardless of the implementation quirks, I don't see any way back for nw, just forward from this approach or something like it.

You've more than earned your pwantz.

Actual testing & analysis of implementation will ensue as soon as I can.

**Comment by tchalvak** [comment]
Ok, got some testing in now:

The rewriting & pathing precedence isn't working right on my end out of the box.  I'm debugging, but are you not running nginx?  And you just tried to duplicate an apache rewrite via nginx for my/nginx's benefit?  
Have you then temporarily deleted deploy/www/clan.php and deploy/www/shop.php and the pages work on your end?

That's the only explanation I can see right away for the behavior I'm getting right away on my end.  I'll fix up the nginx config and see if I can get stuff working (e.g. the javascript # hashes are going to have to be reworked, but that's to be expected).  But but do let me know if I'm off base and there's something else broken in translation!

**Comment by tchalvak** [comment]
For later:
Deprecated: Function split() is deprecated in /srv/ninjawars/deploy/www/front-controller.php on line 34
Fatal error: Class 'app\Controller\Shop.php]Controller' not found in /srv/ninjawars/deploy/www/front-controller.php on line 46

**Comment by tchalvak** [comment]
Urls for testing:
============

### Positive urls:
nw.local/shop
nw.local/clan
nw.local/shop.php
nw.local/clan.php
nw.local/shop
nw.local/shop/view
nw.local/shop/buy

###Bad urls
http://nw.local/shopbobby'-tables

**Comment by tchalvak** [comment]
Success!  We need tests on urls now (always did), but I'm opening that as another issue.
