### ISSUE TITLE
As a developer, I  build the application in a single step

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#351]
Al AC:
- I can build the app from git clone to running application by running ./configure and make
- I can choose a build target other than /deploy/ that can be served by nginx

Roy AC:
- When I save a file, the final system should take that as a sign to compile, I shouldn't have to waste my time switching contexts to do so manually, like an uncivilized savage.
- When I load pages on the dev site, I should be able to rely on them being up to date, because the system should watch for changes and build right away, I shouldn't have to guess whether I'm looking at a current or cached version.

**Comment by tchalvak** [comment]
I don't think this is going to hit for February.

**Comment by tchalvak** [comment]
Marking this EPIC

**Comment by tchalvak** [comment]
I've forgotten what the actual obstacle to this was, unless it is the build target aspect.  @Beagle Thoughts?  Essentially we're talking about using a build system, so maybe grunt or https://webpack.js.org/ would make sense.

**Comment by Beagle** [comment]
Ugh. Node.JS based build system? Seems like overkill. Just a Makefile
target should be fine, no?

**Comment by tchalvak** [comment]
Related to this, I set it up so that deployment of latest only takes a click of a single button (still some bugs to work out with it).

**Comment by tchalvak** [comment]
Have deploybot running and building LIVE on every commit to master branch.

**Comment by tchalvak** [comment]
PR to master runs CI, tests passing is required to merge, merge to master builds to production.

I think this is as good as this one is going to get.
