### ISSUE TITLE
As a developer, I can quickly and easily build the autoloader while still having an optimized autoloader to improve application performance

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#352]
AC:
1) Use -o to optimize composer's autoloader in production
2) Development workflow is not negatively impacted by the requirement of recreation of the autoloader every time a new class is added.

**Comment by tchalvak** [comment]
Shouldn't this just be added in as part of make build or some other similar step?

Maybe an explicit "make live"?

**Comment by tchalvak** [comment]
Done for PROD now.
