### ISSUE TITLE
As a developer, I want Router::route() to be crystal clear.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#358]
The [route function](https://github.com/BitLucid/ninjawars/blob/master/deploy/lib/Router.php#L281) has grown in complexity without much by the way of comments or modularity (and other parts of the `Router` class may need attention as well, it has grown to more than 300 lines).

AC:
- Clearly comment `public static function route()`
- Or split up logic of `public static function route()` for simplicity
- (optional) Simplify other methods
- (optional) Split url settings into their own file for modularity (and so commits that change urls will be clearly different from commits that change `Router` behavior.

**Comment by Beagle** [comment]
Tasks:
1. split routes into a separate file
2. fix routing issue #375
3. Add a doc block for each method
4. add comments inside each method
5. add a doc block for the whole class
