### ISSUE TITLE
As hardcore player Boromir, I have current data on which targets are live so that I can easily attack in fewer clicks

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#360]
> I like this game and want to level up when I get on but always feel fustrated and only kill a little and then leave because I have to study and do other things also ~ 3 days ago

...

> found a few more problems... When I am killing i click attack and then backspace backspace and my turns and kills reverse but when I kill again it goes back to the normal #. that is not too bad but may be confusing if you are killing and using that technique near 5 turns... Also, when I use that technique the ninjas I kill still stay on the page as alive but I can not kill them... this is really inconvenient. I think only if i refresh the page will they go away. I can not kill fast anymore 3 days ago

Possible AC:
- show next targets to attack after killing one?

![screenshot from 2016-02-03 23 47 03](https://cloud.githubusercontent.com/assets/23353/12806054/793bb770-cad0-11e5-9883-ad64e0409c90.png)

**Comment by Beagle** [comment]
The problem described by the user indicates a workflow involving the back button that results in stale data being cached by the browser. I'm not sure what technical solution we can implement to prevent this. Possibly adding explicit cache control headers to pages that pull from the database?

**Comment by tchalvak** [comment]
I think one viable solution is to provide additional live targets at the end of an attack where the current target is dead, so as to eliminate the need to hit the back button.  Separately, it makes sense to tighten up the am I alive or dead ambiguity on the homepage?

**Comment by tchalvak** [comment]
P.S. Standard php pages are in theory NOCACHE, MUST-REVALIDATE anyway, it's just that the back button ignores that (and reasinably so).

**Comment by tchalvak** [comment]
I think this is sufficiently fixed with the fight page.
