### ISSUE TITLE
As a developer, the tags we share should be meaningful and useful

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#362]
AC:
1) consider removing Clan_Rebuild_1
2) consider removing ninjawars-1.6.0
3) consider removing v1.7.4-unstable

**Comment by tchalvak** [comment]
https://github.com/BitLucid/ninjawars/tags?after=v1.7.3-2

Those tags have been deleted/renamed for a while, you need only 'git fetch --prune'

**Comment by Beagle** [comment]
Thanks, I didn't realize. Deleting issue.
