### ISSUE TITLE
As a developer, I understand the development plan by reading the list of milestones

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#364]
AC:
*) We are working on one milestone at a time and do not switch to another milestone mid-stream
*) Milestones are not evergreen, they end at some point
*) Milestones that are useless are deleted from our tracker

**Comment by tchalvak** [comment]
Github's milestone system gets even less love than their issue tracking system does, it's not very transparent or powerful.  In addition, I don't think a timed milestone approach especially suits the amount of development man-hours and part-time hobby-project enjoyment available via the two (2) main developers; every issue takes too variable of a time in that context to attach meaningful timelines even at the single issue level.

Github milestones may contain some marginal utility by being able to be used to group issues in sets based on related functionality, but beyond that...
*shrugs*

**Comment by tchalvak** [comment]
To me, this is a WONTFIX
