### ISSUE TITLE
Shop: As a game designer, I want http://nw.local/shop/buy to return a proper ninja-error message.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#381]
When you hit shop/buy without preparation, it doesn't respond in an in-character way.
![screenshot from 2016-01-14 10 01 02](https://cloud.githubusercontent.com/assets/23353/12327720/040e2e18-baa6-11e5-8685-c08a1994f967.png)

AC:
 - http://nw.local/shop/buy with no post or parameters has in-game page language that makes sense.
 - Page does not imply purchase of blank item; the shopkeeper could complain of a bad purchase request, for example.

**Comment by Beagle** [comment]
BLOCKER: I don't know what it SHOULD do in this case. We need a generic request error solution that doesn't involve 403, 404, or 500.

**Comment by tchalvak** [comment]
Oh, it's not a http return code issue, it's just a minor game logic issue, where it shouldn't try to purchase null items and give some message, etc.  It can return 200 at that point.

**Comment by Beagle** [comment]
I'm proposing that there's a general case for this sort of thing but I don't know what it is yet or how we want to handle it.
