### ISSUE TITLE
Urls: As a SEO consultant, I want arbitrary duplicate url strings prevented.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#382]
http://nw.local/shop/buy_from_amazon_now_for_10_percent_off results in duplicate content.

I did a bisect and this appears to be a regression introduced in the commit:

commit 64cb88f87e8df446d55cbd6c558d67d843cf0b1e
Author: Al Vazquez <al.vazquez@gmail.com>
Date:   Tue Jan 12 21:39:08 2016 -0500

    Add comments and reduce method lengths in Router

:040000 040000 1b5e50aa757ccf30611cfea07ecb81c56d60210e 74d107d4b645056ef21dfbe2dfaa08e79e80b8b9 M	deploy

AC:
- http://nw.local/shop/buy_from_amazon_now_for_10_percent_off should 404.
- http://nw.local/shop/shouldneverexistandstuff should 404.
![screenshot from 2016-01-14 11 25 05](https://cloud.githubusercontent.com/assets/23353/12330119/7e9d8eac-bab1-11e5-873f-80915c35bdfd.png)

**Comment by Beagle** [comment]
This has been fixed, tested, and pushed to master. Please confirm and close.

**Comment by tchalvak** [comment]
Confirmed for that irk (more comprehensive automatic tests pending).

**Comment by tchalvak** [comment]
***url
