### ISSUE TITLE
Ads: As a frontend developer, I want the ads to stop breaking in the console.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#385]
Makes it harder to debug for real errors.

Errors include:

    Uncaught SyntaxError: Unexpected token ILLEGAL
    (program):1 'webkitOfflineAudioContext' is deprecated. Please use 'OfflineAudioContext' instead.
    g-ecx.images-amazon.com/images/G/01/associates/widgets//20070822/US/Flash/DefaultWidget._V1322435481_.swf?ServiceVersion=20070822&MarketPlace=US:1 
    Uncaught SyntaxError: Unexpected token ILLEGAL
    secure.flashtalking.com/frameworks/js/api/2/9/html5API.js:2 Warning: this document has no DOCTYPE declaration. Rendering and features may not adhere to web standards. For more information, see https://developer.mozilla.org/en-US/docs/Quirks_Mode_and_Standards_Mode.

AC:
 - Ads stop erroring in the js console

![screenshot from 2016-01-16 09 09 40](https://cloud.githubusercontent.com/assets/23353/12372781/ef02bbf6-bc30-11e5-9114-e9f6d328e3c6.png)

**Comment by Beagle** [comment]
@tchalvak Cannot reproduce

**Comment by tchalvak** [comment]
Closing wontfix until it pops up as a problem again.
