### ISSUE TITLE
Cachebusting: Unused var in smarty_function_cachebust.  Is $p_tpl necessary?

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#386]
see https://scrutinizer-ci.com/g/BitLucid/ninjawars/inspections/f672535f-b537-4a6a-bbad-af2326666684/issues/files/deploy/lib/plugins/function.cachebust.php?status=new&orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-5640146

**Comment by Beagle** [comment]
comments 1 and 3 can be addressed. Comment 2 I don't believe can be due
to the autoloading feature of smarty plugins. I believe smarty relies on
function signature. I could be wrong and will test my theory.
