### ISSUE TITLE
As a developer, I find all of the request handling logic for NPC combat in a single controller

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#391]
#### AC:
1. npc.php is deleted
2. NPC functionality still works

**Comment by tchalvak** [comment]
https://github.com/BitLucid/ninjawars/commit/20da490875cbf1a0f2da7d7b051f065c30eff726  Closes this.

**Comment by tchalvak** [comment]
Regression where player state is not being altered correctly after attacking an NPC, damn it.

**Comment by tchalvak** [comment]
Got it, it was a UI update issue, not a state-not-being-changed issue: quickstats was missing because I wrote quickstats instead of quickstat, plus alive is required with all npc methods for now.
