### ISSUE TITLE
CI: As a QA, I want the CI to run the functional tests automatically, and have a site to run them against.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#401]
AC:
- CI serves site for functional tests to hit.
- CI runs functional tests automatically.
- Functional tests pass on http 200 tests.
- Functional tests pass on http 404 tests.

**Comment by tchalvak** [comment]
Communicated with codeship, but I'm not sure that we're going to be able to use nginx at all for this.

**Comment by tchalvak** [comment]
Has a large, complicated chain of dependencies right now (e.g. have to compile nginx -and- php5-fpm without root, and who knows what else will turn up), so I'm removing it from the timeline/milestones, as it'll happen when I can make it happen.

**Comment by Beagle** [comment]
@tchalvak How's this going with the static NginX build?

**Comment by tchalvak** [comment]
Rootless nginx works fine.  Php5-fpm is not operational.

**Comment by tchalvak** [comment]
Well, by fine I mean nginx runs as smoothly as can be expected without root.

**Comment by tchalvak** [comment]
wont-fix
