### ISSUE TITLE
Signup: As a player, when I sign up, I don't want ability to join prevented forever by a partial signup process.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#405]
The signup system reports a rejection, but enacts character and account creation anyway, and then trying to continue signup rejects on the grounds of pre-existing character name!

Steps to reproduce:

- Signup with a fresh ninja name, but a stale, duplicate email that should be rejected.
- Receive rejection message "This email already exists in the system."
- Change email to fresh, non-duplicate email.
- Try to sign up again, receive rejection on username already existing!

AC:

- ANY error with signup must NOT create either a ninja or an account.
- Success during signup MUST display a clear prompt to log in or email-confirm.
- An automatic test case should be added: 
  - create bob@example.com & ninjaBlue successfully, then create bob@example.com & ninjaOrange with an Error, finally create bobOrange@example.com & ninjaOrange successfully!

![screenshot from 2016-01-19 10 08 44](https://cloud.githubusercontent.com/assets/23353/12427867/9a56d304-beaf-11e5-8de3-e5b10599df64.png)

**Comment by tchalvak** [comment]
nw=# select players.uname, accounts.active_email from players join account_players on player_id = _player_id join accounts on account_id = _account_id where uname = 'YyaslVir' or active_email = 'blarg@example.com' or account_identity = 'blarg@example.com' or active_email = 'blarg55@example.com';
  uname   |   active_email    
----------+-------------------
 YyaslVir | blarg@example.com
(1 row)

Results in the database for this error.

**Comment by Beagle** [comment]
@tchalvak I don't know how to achieve the goal stated in the story. If the
email already exists in the DB, sign-up should fail based on our current
rules. How would you like to see this resolved?

**Comment by tchalvak** [comment]
The rules are:

- Don't create an account if the email already exists.
- Don't create an account if the ninja name already exists.
- Don't create a player if the ninja name already exists.
- Don't create an account OR player if ANY part of either account or player is invalid (e.g. username too long, email bad, whatever)

In the above case, the signup process was not completed, yet the player & account was created.  The error message was that the email was a duplicate.  It may have been a false positive error (ninja and account were created, yet the error was still displayed).

Both player and account have fresh created_date stamps:

	nw=# select * from accounts left join account_players on account_id = _account_id left join players on player_id = _player_id where active_email = 'blarg@example.com';

	 account_id | account_identity  |                            phash                             |   active_email    | type | operational |        created_date        | last_login | last_login_failure | karma_total |  last_ip  | confirmed | verification_number | oauth_provider | oauth_id | _account_id | _player_id |         last_login         |        created_date        | player_id |  uname   | pname_backup | health | strength | gold | messages | kills | turns | verification_number | active | level | status | member | days | bounty |        created_date        | resurrection_time |    last_started_attack     | energy | avatar_type | _class_id | ki | stamina | speed | karma | kills_gained | kills_used | description | instincts | beliefs | goals | traits 
	------------+-------------------+--------------------------------------------------------------+-------------------+------+-------------+----------------------------+------------+--------------------+-------------+-----------+-----------+---------------------+----------------+----------+-------------+------------+----------------------------+----------------------------+-----------+----------+--------------+--------+----------+------+----------+-------+-------+---------------------+--------+-------+--------+--------+------+--------+----------------------------+-------------------+----------------------------+--------+-------------+-----------+----+---------+-------+-------+--------------+------------+-------------+-----------+---------+-------+--------
	      50702 | blarg@example.com | $2a$10$uZ3BVaQhDGbdRbX0wciKXejy0XFrldwi.WdmaW/y9R95Ad6wlOZdu | blarg@example.com |    0 | t           | 2016-01-19 09:42:34.058456 |            |                    |           0 | 127.0.0.1 |         0 | 4939                |                |          |       50702 |     192088 | 2016-01-19 09:42:34.308248 | 2016-01-19 09:42:34.308248 |    192088 | YyaslVir |              |    150 |        5 |  100 |          |     0 |   180 |                4939 |      1 |     1 |      1 |      0 |    0 |      0 | 2016-01-19 09:42:33.934668 |                 6 | 2016-01-19 09:42:33.934668 |      0 |           1 |         4 |  0 |       5 |     5 |     0 |            0 |          0 |             |           |         |       | 
	(1 row)

This may or may not be an entirely valid ninja and account.  The problem comes that the potential player is left in the signup form with no prompt to log in or confirm their account, and all further attempts to sign up with their email or ninja name will be rejected!  Because those entries now exist.

**Comment by tchalvak** [comment]
Comment edited for clarity (if you're following via email).

**Comment by tchalvak** [comment]
Acceptance Criteria Clarified.

**Comment by Beagle** [comment]
@tchalvak This behavior is not reproducible in the current build on master

**Comment by tchalvak** [comment]
Yes, I know my reproduction steps don't reproduce the problem, but I expect that is a failing of my reproduction steps, not necessarily the bug.  I'm going to try to get 100% coverage on everything signup and also see if I can break signup with more manual testing.  The destructive nature of the bug warrants it, I think.

**Comment by tchalvak** [comment]
Tested again, closing.
