### ISSUE TITLE
CSS: As a designer/dev, I want to run the css through csslint.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#406]
http://csslint.net/

AC:

- Fix a few errors/warnings from css lint.

![screenshot from 2016-01-20 14 57 08](https://cloud.githubusercontent.com/assets/23353/12461284/1a7188a0-bf86-11e5-994c-dc8aa6310573.png)

**Comment by tchalvak** [comment]
There were two actual syntax errors with ; semicolons that should have been : colons, but I fixed those already!

**Comment by Beagle** [comment]
Closed via #407
