### ISSUE TITLE
Multi-clan membership needs to be clarified.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#43]
Currently it is possible under the system (e.g. in the database a char can be added to clan A and clan B, and show up in both), which should be codified and preferrably made sign of distinction, non-trivial to achieve.

**Comment by Beagle** [comment]
@tchalvak I propose we close this issue. The reason the database schema provides a separate entity for clan membership is not to allow many-to-many but instead to store additional attributes on the relationship (which requires the relationship be represented as an entity). I do not feel multi-clan membership is within the scope of this project at this time.

**Comment by tchalvak** [comment]
I will simply reopen if I get the ambition to work on this.
