### ISSUE TITLE
Guard Npc: As a game designer, I want to ensure that guard2 is at least as damaging as guard1.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#435]
It seems that the original guard "steals" some of the attacker's strength, and rewards some of that in gold back, as well.

http://nw.local/npc/attack/guard/
http://nw.local/npc/attack/guard2/

AC:
 - .... ..... .... Variance of the random damage difference between a guard1 and a guard2 is only +-10% over 30 damage calls (this is a unit test)
- Maybe the randomness there is to unpredictable to unit test, so test max damage better instead, but something seems to be going on.

![screenshot from 2016-02-01 17 53 10](https://cloud.githubusercontent.com/assets/23353/12734155/b36c27ce-c90c-11e5-8d46-a13df06fcaab.png)

![screenshot from 2016-02-01 17 53 39](https://cloud.githubusercontent.com/assets/23353/12734178/eab6da08-c90c-11e5-8b7b-d1b63c932cc0.png)

(I know these are just random instances, but still, it feels off because of the strength addition that only happens on the guard1)

**Comment by tchalvak** [comment]
Related to #528.

**Comment by Beagle** [comment]
This story is impossible as written. Guard2 is static, Guard1 is dynamic. Guard1's damage is dependent on the strength of the player attacking so unless Guard2 gets a strength boost to put it over the largest possible strength of a player, this cannot be fixed without getting rid of the Guard1 dynamic strength feature. This story is blocked until you can provide clarity as to your desired result

**Comment by tchalvak** [comment]
Guard2 is dynamic via trait: match_strength.  But I think since all NPCs will require rebalancing, I'm going to close this issue in favor of the whole rebalancing needed for communism.
