### ISSUE TITLE
Debugging: As a dev, I want errors not to be masked by a 404 or 200 status.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#446]
Hard to replicate this, this continuously happens when debugging, for example when introducing some kind of error within player.php it'll show a 404 for a valid url instead of throwing out a continous error or whatever.

AC:
- Error throws a 50x status.
- Non-existent url throws a 404 status.
- Captured exceptions in front-controller.php should throw a custom exception only for valid 404 cases.
- 404 exceptions thrown should show 404 page, but not-really-404 exceptions in the router should just be re-thrown.
- (optional) backup database, dropdb nw, homepage should 500 error

**Comment by tchalvak** [comment]
Related:

http://nw.local/homepage/splash

Throws:

Fatal error: Call to private method NinjaWars\core\control\HomepageController::splash() from context 'NinjaWars\core\Router' in /srv/ninjawars/deploy/lib/Router.php on line 223

**Comment by tchalvak** [comment]
This also falsely returns 200 status code from an uncaught exception on dev.

**Comment by tchalvak** [comment]
Hmmm, that url seems to be unfixed now:

http://nw.local/homepage/splash

**Comment by Beagle** [comment]
@tchalvak Is there anything more to be done here?

**Comment by tchalvak** [comment]
Fixed, will make new, separate issue for error_handling refactor.
