### ISSUE TITLE
Splash: Make splash page and intro page displayable without any database connection.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#486]
AC:
- having no database
- splash page still displays
- intro page still displays
- (optional) make the splash and intro page pages well cache-able

Example error that made me realize this (when the database was legit down):

```

2016/02/17 12:56:42 [error] 1562#0: *7636 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'The Database connection failed.' in /srv/ninjawars/deploy/lib/data/DatabaseConnection.php:25
Stack trace:
#0 /srv/ninjawars/deploy/lib/data/DatabaseConnection.php(32): NinjaWars\core\data\DatabaseConnection->__construct()
#1 /srv/ninjawars/deploy/lib/data/lib_db.php(19): NinjaWars\core\data\DatabaseConnection::getInstance()
#2 /srv/ninjawars/deploy/lib/data/lib_db.php(50): query('(SELECT count(s...', Array, false)
#3 /srv/ninjawars/deploy/lib/control/lib_player_list.php(64): query_array('(SELECT count(s...')
#4 /srv/ninjawars/deploy/www/splash.php(9): member_counts()
#5 /srv/ninjawars/deploy/www/index.php(11): require_once('/srv/ninjawars/...')
#6 /srv/ninjawars/deploy/lib/Router.php(60): include('/srv/ninjawars/...')
#7 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
  thrown in /srv/ninjawars/deploy/lib/data/DatabaseConnection.php on line 25" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net"
```

**Comment by Beagle** [comment]
@tchalvak What's the difference between the splash and the intro page. PR #494 removes the dependency on the DB from HomePageController->splash() I don't see how you can remove the dependency for the index though, as it has health bars. Please advise as this story may already be resolved by my PR

**Comment by tchalvak** [comment]
Splash page for people who are logged out.
Homepage for people who are logged in.
Intro page for static game intro content that is the default view inside the iframe for both cases.

Only want to remove dependency on the database for /splash and /intro, not for /index, as nice as that might be.

**Comment by tchalvak** [comment]
Sadly when I delete my database:

```
pg_dump nw > nw-dev-2016-02-28.sql
dropdb nw
```

And then load the homepage, it actually 404s instead of 500 erroring, making it hard to find what things are creating problems.

**Comment by Beagle** [comment]
@tchalvak What else needs to be done here?

**Comment by tchalvak** [comment]
All the AC still.

**Comment by tchalvak** [comment]
https://splash.ninjawars.net/ exists now, not yet fully in use.

**Comment by tchalvak** [comment]
![screenshot from 2018-09-02 08-48-55](https://user-images.githubusercontent.com/23353/44956132-0d350380-ae8d-11e8-8ff7-f46293086f52.png)

**Comment by Beagle** [comment]
Don't advertise for Starbucks unless they're paying you!

**Comment by tchalvak** [comment]
Haha, yes, I have to find a more "ninja" themed background image, hard to find good stock imagery that fits the ninjawars theme.  However, before I can use this splash page at all, I have to figure out how I can redirect or proxy the splash page with the current ninjawars approach to a homepage.  Tricky.

**Comment by tchalvak** [comment]
In progress with https://shell.ninjawars.net
