### ISSUE TITLE
As a logged-out user, I should not see a form for offering bounty on ninja

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#491]

**Comment by tchalvak** [comment]
![screenshot from 2016-02-21 16 04 33](https://cloud.githubusercontent.com/assets/23353/13205381/e8bd0256-d8b4-11e5-86e0-42e3f40e2fa8.png)

**Comment by tchalvak** [comment]
Currently trying to offer logged-out bounty errors (with blank white page).
