### ISSUE TITLE
Logged error: Mar 01 00:20:40 megaman error.log: 2016/03/01 00:20:12 [error] 23124#0: *554599 FastCGI sent in stderr: "PHP message: PHP Warning: Division by zero in /srv/ninjawars/deploy/lib/control/Player.class.php on line 380

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#534]

**Comment by tchalvak** [comment]
Mar 01 00:20:40 megaman error.log: PHP message: PHP Notice: Undefined variable: items in /srv/ninjawars/deploy/lib/control/ApiController.php on line 226" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /api.php?type=index&jsoncallback=jQuery21102882223227061331_1456798575452&_=1456798575459 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/"
Mar 01 00:21:08 megaman error.log: 2016/03/01 00:20:40 [error] 23124#0: *554624 FastCGI sent in stderr: "PHP message: PHP Warning: Division by zero in /srv/ninjawars/deploy/lib/control/Player.class.php on line 380
Mar 01 00:21:08 megaman error.log: PHP message: PHP Notice: Undefined variable: items in /srv/ninjawars/deploy/lib/control/ApiController.php on line 226" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /api.php?type=index&jsoncallback=jQuery21102882223227061331_1456798575452&_=1456798575460 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/"

**Comment by Beagle** [comment]
@tchalvak Cannot reproduce. Please advise

**Comment by tchalvak** [comment]
Mar 18 21:13:52 megaman error.log: 2016/03/18 21:12:41 [error] 13642#0: *515428 FastCGI sent in stderr: "PHP message: PHP Warning: Division by zero in /srv/ninjawars/deploy/lib/control/Player.class.php on line 491" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /api.php?type=index&jsoncallback=jQuery21104475211316386316_1458337731811&_=1458337732243 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/"

**Comment by tchalvak** [comment]
At a guess, I'd say the reproduce procedure for this is: Log out in a separate tab, wait for the api to fail on trying to get a Player object on calls when the player is not logged in.  I tightened up the login by using Player::find in the above referenced commit and this should be resolved.
