### ISSUE TITLE
MIssing template error: $weakness_error is not being utilized in npc controller.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#544]
Scrutinizer says that the "weakness_error" var is not being used, though it should be a type of rejection for low level players.

see https://scrutinizer-ci.com/g/BitLucid/ninjawars/inspections/f4c112f9-837a-4c9e-8ffb-e7ca1d9541c3/issues/files/deploy/lib/control/NpcController.php?status=new&orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-12648107

**Comment by Beagle** [comment]
@tchalvak This is already handled by the samurai template it seems.
