### ISSUE TITLE
Npcs: $attacker_level var removed almost everywhere, but not everywhere.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#557]
AC:
- $attacker_level needs to be replaced in NpcController since it is uninitialized.

https://github.com/BitLucid/ninjawars/commit/bbba0835e16c334598c0de1e764c72c8bc0f7ce0#diff-0f0376bea4b4e55e9ecb17e75772e5a0R189

**Comment by Beagle** [comment]
@tchalvak This no longer appears to be an issue. Please review.

**Comment by tchalvak** [comment]
Seems so.
