### ISSUE TITLE
Bounty: player reports bounty limit of 5,000 or whatever exceeded on live.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#571]
Says killed another player with a bounty of 100,000

AC:
- Get some form of runbountyexchange running on npcs so that gaining bounty from them respects a bounty limit.

**Comment by tchalvak** [comment]
Hmmm, closing as can't replicate for now.

**Comment by tchalvak** [comment]
Reopened.

Do NPCs no longer limit bounty attachable to a character?  Needs investigation.

**Comment by tchalvak** [comment]
@beagle I think you may have regressed the bounty limits on npcs when replacing bounty code in npcs.

**Comment by Beagle** [comment]
confirmed: NPC bounty behavior does not respect bounty cap

**Comment by tchalvak** [comment]
It doesn't any longer, ya.

This bug is important because it's causing an influx of gold into the economy that won't go away after.
