### ISSUE TITLE
Special characters allowed in clan names, somehow.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#66]

**Comment by Beagle** [comment]
@tchalvak This issue is no longer present when renaming clans. If you have other places where this problem exists, please open new issues for them. I propose closing this issue without further action.

**Comment by tchalvak** [comment]
Is there a test for this to avoid regression?

**Comment by Beagle** [comment]
No. Is that the acceptance criteria for closing this issue?
