### ISSUE TITLE
Events: Check whether events SysMsg still work, or just fail, and whether 'SysMsg' 'SysMsg' events work or can be removed.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#687]
https://github.com/BitLucid/ninjawars/pull/679/commits/9f9e699c390e7520404c3e62ba47e5fc45220be5#diff-bb59b885602cd9ff922dd62c0d7ce7e7R281
https://github.com/BitLucid/ninjawars/pull/679/commits/9f9e699c390e7520404c3e62ba47e5fc45220be5#diff-bb59b885602cd9ff922dd62c0d7ce7e7R121

Also "A Stealthed Ninja", which certainly doesn't work as a Stealthed Ninja, but does it even work as SysMsg?  Does a 0 id event actually work as SysMsg?

AC:
- Events that originate from the player, but have no valid "sender" per se, should show self as sender.
- **Self-category** examples include; dying while attacking an npc, dying during a duel I initiate, maybe clan leave, kick, and disband.
- **Unknown Category** examples include; being single-attacked by a stealthed ninja, being item-attacked by a stealthed ninja. (not being dueled by a stealthed ninja)
- **Other Person Category** examples include; being attacked by Bob, getting a clan invite from Bob, getting dueled by bob.

Currently, everything in the **Self-category** appears to have been brokenly shunted into the **Unknown Category**.

**Comment by Beagle** [comment]
Anything I can do to help you test this?

**Comment by tchalvak** [comment]
@Beagle I added some AC if that helps.  Seems pretty clear that you've uncovered a major bug with how events are being handled, resulting in a large number of events being lost.

![screenshot from 2016-04-24 22 04 46](https://cloud.githubusercontent.com/assets/23353/14772400/bdacf8f8-0a6b-11e6-8d59-bfee4643c640.png)

**Comment by tchalvak** [comment]
Ok, I think this is actually all good now, assuming the second column doesn't prevent putting in 0 for sysmsg, it's just an event to nowhere like before.
