### ISSUE TITLE
Shrine thinks I'm logged out when I try to heal

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#702]

**Comment by Beagle** [comment]
for some reason I had to log out and log back in

**Comment by tchalvak** [comment]
Yeah, that describes the behavior that I was initially experiencing with the auth branch in general.

**Comment by Beagle** [comment]
It makes sense as a new session variable (authenticated) was added and we were already logged in so we didn't have the variable. Logging out and back in fixes the issue.

**Comment by tchalvak** [comment]
Ahah, yes, that probably does explain it.

On Sat, Apr 9, 2016 at 10:06 AM, Beagle <notifications@github.com> wrote:

> It makes sense as a new session variable (authenticated) was added and we
> were already logged in so we didn't have the variable. Logging out and back
> in fixes the issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/BitLucid/ninjawars/issues/702#issuecomment-207794073>
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."

**Comment by tchalvak** [comment]
Actually, doesn't completely describe it, because I could refresh the whole page, and it still throught I was logged in on the main page, but it would say I wasn't logged in in the internal page.  Is there a solution to this so that players won't experience the same problem, and be confused/dismayed by it.

**Comment by Beagle** [comment]
Probably should just wipe all sessions when this gets deployed and force
everyone to log in again. And yes, it does describe it because not every
place uses authenticated to check status. Many still check player_id
