### ISSUE TITLE
Can't use Tiger Salve

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#711]

**Comment by Beagle** [comment]
2016/04/09 16:37:33 [error] 3844#3844: *41925 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: AttackLegal required turns not specified.' in /  home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/control/AttackLegal.php:54                                                                                                                                 
Stack trace:                                                                                                                                                                                                     
#0 /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/control/InventoryController.php(140): NinjaWars\core\control\AttackLegal->__construct(Object(NinjaWars\core\data\Player),                              Object(NinjaWars\core\data\Player), Array)                                                                                                                                                                       
#1 /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/Router.php(210): NinjaWars\core\control\InventoryController->selfUse()                                                                                 
#2 /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/Router.php(71): NinjaWars\core\Router::execute('inventory', 'self_use')                                                                                
#3 /home/beagle/projects/gamedev/nw1/ninjawars/deploy/www/front-controller.php(18): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request))                                               
#4 {main}                                                                                                                                                                                                        
  thrown in /home/beagle/projects/gamedev/nw1/ninjawars/deploy/lib/control/AttackLegal.php on line 54" while reading response header from upstream, client: 127.0.0.1, server: nw.localhost, request: "GET /item/self_use/8 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "nw.localhost", referrer: "http://nw.localhost/inventory"

**Comment by tchalvak** [comment]
Ah, yeah, you have to run the migration.
