### ISSUE TITLE
Menu: As a designer, I want sketches for a whole menu replacements, to reduce space and increase clarity.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#737]
AC:
- let's get at least three sketches, discuss them, and see if we can find a suitable replacement.

@beagle

**Comment by tchalvak** [comment]
Top pages via google analytics.

![screenshot from 2016-04-13 12 45 17](https://cloud.githubusercontent.com/assets/23353/14501678/9cbf6364-0175-11e6-9042-3b14f24195af.png)

**Comment by tchalvak** [comment]
![nw_mobile_layout_sketch](https://cloud.githubusercontent.com/assets/23353/14502872/6fff6364-017b-11e6-839e-2aa48ff2169c.png)

**Comment by tchalvak** [comment]
![nw_long_layout_with_key](https://cloud.githubusercontent.com/assets/23353/14502918/b6488e0e-017b-11e6-8561-7dd9dedc64c6.jpg)

**Comment by Beagle** [comment]
Looks like everyone uses the list!

**Comment by tchalvak** [comment]
@beagle You willing to contribute at least one of three sketches/UX priority lists or whatever you called 'em?  I could use an extra perspective beyond my own to make a more effective final result.

**Comment by Beagle** [comment]
@tchalvak  Maybe I can put one together this week.

**Comment by tchalvak** [comment]
I think this is closed at this point, and we've moved the UI to bootstrap, though we really really need to still handle a highly visible health bar, that's a major regression right now.
