### ISSUE TITLE
AttackController::combat is not using the $required_turns value that is passed to the method (immediately overwrites to default of 0).

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#785]
see https://scrutinizer-ci.com/g/BitLucid/ninjawars/inspections/e746906b-8470-4e95-a0db-91d7a3c29372/issues/files/deploy/lib/control/AttackController.php?status=new&orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-19326455

**Comment by Beagle** [comment]
Seems to be used on line 151

**Comment by tchalvak** [comment]
Sorry, to clarify: The $required_turns param is always overwritten to 0 in the beginning of the method.
