### ISSUE TITLE
As a user, I want to be able to reset my password when I forget it.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#79]
If a player wants access to their account, and they have forgotten their totally inconsequential throwaway password that they created specifically for ninjawars, there is no way for them to retrieve that information.

We need to provide the basic functionality of a password reset system, via email ideally.

**Comment by tchalvak** [comment]
Work in progress on password_reset branch.

**Comment by Beagle** [comment]
@tchalvak Is this done now?

**Comment by tchalvak** [comment]
Just on hold for now.

On Sun, Oct 25, 2015 at 11:02 AM, Beagle <notifications@github.com> wrote:

> @tchalvak <https://github.com/tchalvak> Is this done now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BitLucid/ninjawars/issues/79#issuecomment-150932288>.
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."

**Comment by Beagle** [comment]
Why on hold? You merged in the code and the feature is live, correct?

**Comment by tchalvak** [comment]
No.

**Comment by tchalvak** [comment]
Had a working implementation but have to fully refactor and squash commit now.  60% complete.

**Comment by tchalvak** [comment]
Need to:

- Use $command for the controller actions.
- Use eloquent for the model pulling from the database.

**Comment by tchalvak** [comment]
https://github.com/BitLucid/ninjawars/pull/408  Will close this issue once complete.  Still gotta get some tests and functionality passing.
