### ISSUE TITLE
When a user tries to update clan avatar, it simply errors with: "That avatar url is not valid."

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#915]
![screenshot_2018-12-29_21-22-45](https://user-images.githubusercontent.com/23353/50543828-03f44300-0bb0-11e9-831f-ba58e1cfe8ba.png)

Reported by: deadpool

**Comment by deadpool100** [comment]
why does the adress bar show "Not Secure: ___" O,O;

**Comment by tchalvak** [comment]
@deadpool100 Yeah, that is a seperate issue ( https://github.com/BitLucid/ninjawars/issues/842 ) where browsers have updated to disallow non-https sites that have a login page, so that’s something where I have to do a lot of work to update the game to make it always secure at all times.

**Comment by tchalvak** [comment]
Fixed with imgur clan avatar uploading.
