### ISSUE TITLE
Use this Tiger Salve Image made a year or two ago

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#982]
![tiger_salve](https://user-images.githubusercontent.com/23353/90796960-ff792280-e2dd-11ea-997d-ca2cd29f905d.png)

**Comment by tchalvak** [comment]
Same with the others, no idea why I didn’t use them or whatever. Maybe they’re not in the shop.

https://opengameart.org/content/sake-flask-and-cup

**Comment by Beagle** [comment]
😂

**Comment by tchalvak** [comment]
Never mind, the images are in use, just sake as an item isn’t live.
